---

- block:
    - name: Install dependencies apt
      apt:
        update_cache: true
        name: "{{ grafana_dependencies }}"
        state: present
      register: _install_dep_packages
      until: _install_dep_packages is succeeded
      retries: 5
      delay: 2
      when:
        - ansible_pkg_mgr == "apt"

    - name: Install dependencies other
      package:
        name: "{{ grafana_dependencies }}"
        state: present
      register: _install_dep_packages
      until: _install_dep_packages is succeeded
      retries: 5
      delay: 2
      when:
        - ansible_pkg_mgr != "apt"

- name: Remove conflicting grafana packages
  package:
    name: grafana-data
    state: absent
  register: _old_grafana_pkgs

- name: Clean apt cache
  command: apt clean
  when:
    - _old_grafana_pkgs is changed
    - ansible_pkg_mgr == "apt"

- name: Add Grafana repository file [RHEL/CentOS]
  template:
    src: "{{ grafana_yum_repo_template }}"
    dest: "/etc/yum.repos.d/{{ grafana_yum_repo_template | basename | regex_replace('\\.j2$', '') }}"
    force: true
    backup: true
  when:
    - ansible_pkg_mgr in ['yum', 'dnf']
    - grafana_manage_repo

- block:
    - name: Import Grafana GPG signing key [Debian/Ubuntu]
      apt_key:
        url: "https://packages.grafana.com/gpg.key"
        state: present
        validate_certs: false
      register: _add_apt_key
      until: _add_apt_key is succeeded
      retries: 5
      delay: 2

    - name: Add Grafana repository [Debian/Ubuntu]
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        update_cache: true
      register: _update_apt_cache
      until: _update_apt_cache is succeeded
      retries: 5
      delay: 2
  when:
    - ansible_pkg_mgr == "apt"
    - grafana_manage_repo
  environment: "{{ grafana_environment }}"

- name: Install Grafana from repository if no file set
  package:
    name: "{{ grafana_package }}"
    state: "{{ (grafana_version == 'latest') | ternary('latest', 'present') }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2
  notify: restart grafana
  when: grafana_package_file | default('') | length <= 0

- name: Download and install exact grafana package
  apt:
    deb: "{{ grafana_package_file }}"
  when: grafana_package_file | default('') | length > 0
